services:
  - type: web
    name: backend-service
    env: node
    buildCommand: cd backend && yarn install
    startCommand: cd backend && yarn start
    
  - type: web
    name: frontend-service
    env: node
    buildCommand: cd frontend && yarn install && yarn build
    startCommand: cd frontend && yarn preview
